In [18]:
import pandas as pd
import glob
import sqlite3

db_path = r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\database\olist.db"

conn = sqlite3.connect(db_path)

csv_files = glob.glob(r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\*csv")

datasets = {}

for file in csv_files:
    data = pd.read_csv(file)
    datasets[file] = data

In [19]:
customers = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\olist_customers_dataset.csv"]
geolocation = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\olist_geolocation_dataset.csv"]
order_items = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\olist_order_items_dataset.csv"]
order_payments = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\olist_order_payments_dataset.csv"]
order_reviews = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\olist_order_reviews_dataset.csv"]
orders = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\olist_orders_dataset.csv"]
products = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\olist_products_dataset.csv"]
sellers = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\olist_selllers_dataset.csv"]
category_translation = datasets[r"C:\Users\Abdul\Documents\VS_code_projects\OLIST_Data_Cleaning\data\cleaned\product_category_name_translation.csv"]

In [20]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]
orders[date_columns] = orders[date_columns].apply(pd.to_datetime)



review_date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]
order_reviews[review_date_columns] = (
    order_reviews[review_date_columns]
    .apply(pd.to_datetime)
)

In [21]:
orders[date_columns].dtypes

order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [22]:
order_reviews[review_date_columns].dtypes

review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [25]:
customers.to_sql("customers", conn, if_exists = "replace", index = False)
geolocation.to_sql("geolocation", conn, if_exists = "replace", index = False)
order_items.to_sql("order_items", conn, if_exists = "replace", index = False)
order_payments.to_sql("order_payments", conn, if_exists = "replace", index = False)
order_reviews.to_sql("order_reviews", conn, if_exists = "replace", index = False)
orders.to_sql("orders", conn, if_exists = "replace", index = False)
products.to_sql("products", conn, if_exists = "replace", index = False)
sellers.to_sql("Sellers", conn, if_exists = "replace", index = False)
category_translation.to_sql("category_translation", conn, if_exists = "replace", index = False)

71

In [35]:
query = """


PRAGMA table_info(orders)

"""

df = pd.read_sql(query, conn)
df

   cid                           name       type  notnull dflt_value  pk
0    0                       order_id       TEXT        0       None   0
1    1                    customer_id       TEXT        0       None   0
2    2                   order_status       TEXT        0       None   0
3    3       order_purchase_timestamp  TIMESTAMP        0       None   0
4    4              order_approved_at  TIMESTAMP        0       None   0
5    5   order_delivered_carrier_date  TIMESTAMP        0       None   0
6    6  order_delivered_customer_date  TIMESTAMP        0       None   0
7    7  order_estimated_delivery_date  TIMESTAMP        0       None   0

In [36]:
query = """


PRAGMA table_info(order_reviews)

"""

df = pd.read_sql(query, conn)
df

   cid                     name       type  notnull dflt_value  pk
0    0                review_id       TEXT        0       None   0
1    1                 order_id       TEXT        0       None   0
2    2             review_score    INTEGER        0       None   0
3    3     review_comment_title       TEXT        0       None   0
4    4   review_comment_message       TEXT        0       None   0
5    5     review_creation_date  TIMESTAMP        0       None   0
6    6  review_answer_timestamp  TIMESTAMP        0       None   0

In [37]:
query = """

SELECT name
FROM sqlite_master
WHERE type = "table"

"""

df = pd.read_sql(query, conn)
df

                   name
0             customers
1           geolocation
2           order_items
3        order_payments
4         order_reviews
5                orders
6              products
7               Sellers
8  category_translation

In [47]:
query = """
SELECT COUNT(*) AS row_count
FROM customers;
"""

pd.read_sql(query, conn)

   row_count
0      99441

In [48]:
query = """
SELECT COUNT(*) AS row_count
FROM geolocation;
"""

pd.read_sql(query, conn)

   row_count
0     738332

In [49]:
query = """
SELECT COUNT(*) AS row_count
FROM order_items;
"""

pd.read_sql(query, conn)

   row_count
0     112650

In [50]:
query = """
SELECT COUNT(*) AS row_count
FROM order_payments;
"""

pd.read_sql(query, conn)

   row_count
0     103886

In [51]:
query = """
SELECT COUNT(*) AS row_count
FROM order_reviews;
"""

pd.read_sql(query, conn)

   row_count
0      99224

In [52]:
query = """
SELECT COUNT(*) AS row_count
FROM orders;
"""

pd.read_sql(query, conn)

   row_count
0      99441

In [53]:
query = """
SELECT COUNT(*) AS row_count
FROM products;
"""

pd.read_sql(query, conn)

   row_count
0      32951

In [54]:
query = """
SELECT COUNT(*) AS row_count
FROM sellers;
"""

pd.read_sql(query, conn)

   row_count
0       3095

In [55]:
query = """
SELECT COUNT(*) AS row_count
FROM category_translation;
"""

pd.read_sql(query, conn)

   row_count
0         71

In [56]:
conn.close()